# This is a basic workflow to help you get started with Actions

name: fetch-data-cron

on:
#   schedule:
#     - cron: '0 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Fetch from public API
        run: npx ts-node ./lib/fetch-data.ts