# This is a basic workflow to help you get started with Actions

name: fetch-data-cron

on:
#   schedule:
#     - cron: '0 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npx ts-node ./lib/fetch-data.ts